xquery version "3.1";
module namespace app="http://splitleaf.org/templates";

import module namespace templates="http://exist-db.org/xquery/html-templating";
import module namespace config="http://splitleaf.org//config" at "config.xqm";

declare namespace mei="http://www.music-encoding.org/ns/mei";
declare namespace tei="http://www.tei-c.org/ns/1.0";

(:~
 : This is a sample templating function. It will be called by the templating module if
 : it encounters an HTML element with an attribute: data-template="app:test" or class="app:test" (deprecated). 
 : The function has to take 2 default parameters. Additional parameters are automatically mapped to
 : any matching request or function parameter.
 : 
 : @param $node the HTML node with the attribute which triggered this call
 : @param $model a map containing arbitrary data - used to pass information between template calls
 :)

(:  :declare function app:test($node as node(), $model as map(*)) {
    <p>Dummy template output generated by function app:test at {current-dateTime()}. The templating
        function was triggered by the data-template attribute <code>data-template="app:test"</code>.</p>
};:)

declare function app:source($node as node(), $model as map(*)) {
    let $list :=
        for $i in collection("/db/texts/")//tei:editionStmt/tei:edition/tei:title
        group by $d := $i/text()
        where $i/@type = "short"
        return $d
    let $json := serialize($list, map{"method":"json"})
    return
        <script type="text/javascript">
            var pssourceList = {$json};
        </script>
};

declare function app:get-texts($node as node(), $model as map(*), $source as xs:string){
    for $t in collection ("db/texts")
    order by fn:number(fn:substring($text//tei:titleStmt/tei:title/text(), 7))
    where $t//tei:editionStmt/tei:edition/tei:title = $source 
    return
        <option value="{$text//tei:titleStmt/tei:title/text()}" id="{base-uri($text)};{$text//tei:div/@met};{$text//tei:note[2]};{$text//tei:lg/@n}"/>
};

declare function app:menu($node as node(), $model as map(*)) {
            for $text in collection("/db/texts")
                order by fn:number(fn:substring($text//tei:titleStmt/tei:title/text(), 7))
                return
                    <option value="{$text//tei:titleStmt/tei:title/text()}" id="{base-uri($text)};{$text//tei:div/@met};{$text//tei:note[2]};{$text//tei:lg/@n}"/>
            
            (:for $text in collection("/db/texts")
            let $m := $text//tei:div/@met
            group by $m
            order by $m
            return
                <optgroup label="{$m}">
                    {for $t in $text
                    order by fn:number(fn:substring($t//tei:titleStmt/tei:title/text(), 7))
                    return
                        <option value="{$t//tei:titleStmt/tei:title/text()}" id="{base-uri($t)};{$t//tei:div/@met};{$t//tei:note[2]};{$t//tei:lg/@n}">{$t//tei:div/@met} {$t//tei:titleStmt/tei:title/text()}</option>}
                </optgroup>:)
};

declare function app:metres($node as node(), $model as map(*)){
    for $text in collection("/db/texts")
    group by $met := $text//tei:div/@met
    order by count($text) descending
    return
        <option value="{$met}"/>
};

(: Corrected app:page-title in app.xql :)
declare function app:page-title($node as node(), $model as map(*), $default as xs:string?) as map(*) {
    let $context := request:get-context-path()
    let $prefix := request:get-attribute("$exist:prefix")
    let $controller := request:get-attribute("$exist:controller")
    
    (: Join parts and ensure there are no double slashes :)
    let $base := replace(concat($context, $prefix, $controller, "/"), "/+", "/")
    
    return map { 
        "page-title": ($default[. != ""], "Digital Splitleaf")[1], 
        "base-url": $base 
    }
};

declare function app:tab-active($node as node(), $model as map(*), $tab as xs:string) as element() {
    let $uri     := request:get-uri()
    let $active  := contains($uri, $tab)
    let $class   := if ($active) then "tablink active" else "tablink"
    return
        element { node-name($node) } {
            $node/@* except $node/@class,
            attribute class { $class },
            $node/node()
        }
};